### ISSUE TITLE
Cloudflare DDOS protection breaks compiling

### ISSUE THREAD

**Issue by Banaanae** [CCCC-L/Action-Ahk2Exe#1]
autohotkey.com added cloudflare protection, which now breaks getting v2.
https://github.com/mmikeww/AHK-v2-script-converter/actions/runs/12441347986/job/34738101320

I'd did a quick look and it doesn't seem possible to use `Invoke-WebRequest` with cloudflare, maybe a mirror site?
Or maybe just make a post on the forums?

**Comment by Banaanae** [comment]
https://www.autohotkey.com/boards/viewtopic.php?f=81&t=134991

**Comment by Banaanae** [comment]
For anyone here in the future
https://github.com/marketplace/actions/compile-ahk-script

**Comment by CCCC-L** [comment]
Thanks for the advice.
